#!/usr/bin/env python3
"""Run a single, shared Windows workspace through UMU and DW-Proton."""

from __future__ import annotations

import configparser
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import time
import unicodedata


APP = "win-run"
DEFAULT_PROTON = "@protonPath@"
DEFAULT_UMU = "@umuRun@"
ENTRY_ID_RE = re.compile(r"^wr1-[0-9a-f]{24}$")
WINDOWS_PATH_RE = re.compile(r"^[A-Za-z]:\\")
ICON_SIZE_RE = re.compile(r"^(\d+)x(\d+)$")
UNINSTALL_RE = re.compile(r"(?:^|\b)(?:uninstall(?:er)?|remove)(?:\b|$)", re.IGNORECASE)


class WinRunError(Exception):
    pass


def workspace() -> Path:
    value = os.environ.get("WIN_RUN_WORKSPACE", "~/Games/win-run/default")
    return Path(value).expanduser().resolve(strict=False)


def legacy_workspace() -> Path:
    value = os.environ.get("WIN_RUN_LEGACY_WORKSPACE", "~/Games/umu/exe-universal")
    return Path(value).expanduser().resolve(strict=False)


def shortcuts_root(root: Path) -> Path:
    return root / "drive_c" / "proton_shortcuts"


def desktop_value(value: str) -> str:
    """Decode the escapes permitted in Desktop Entry string values."""
    result: list[str] = []
    index = 0
    escapes = {"s": " ", "n": "\n", "t": "\t", "r": "\r", "\\": "\\", '"': '"'}
    while index < len(value):
        char = value[index]
        if char != "\\":
            result.append(char)
            index += 1
            continue
        if index + 1 >= len(value) or value[index + 1] not in escapes:
            raise WinRunError("unsupported escape in Desktop Entry value")
        result.append(escapes[value[index + 1]])
        index += 2
    return "".join(result)


def shortcut_from_exec(value: str) -> str:
    """Accept only the single-path Exec form generated by DW-Proton."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        value = value[1:-1]
    elif any(char.isspace() for char in value):
        raise WinRunError("Desktop Entry Exec must contain exactly one shortcut path")
    shortcut = desktop_value(value)
    if not WINDOWS_PATH_RE.match(shortcut) or not shortcut.casefold().endswith(".lnk"):
        raise WinRunError("Desktop Entry Exec is not a Windows shortcut")
    return shortcut


def shortcut_identity(shortcut: str) -> str:
    normalized = unicodedata.normalize("NFC", shortcut).replace("/", "\\")
    normalized = re.sub(r"\\+", r"\\", normalized)
    return normalized.casefold()


def entry_id(shortcut: str) -> str:
    identity = shortcut_identity(shortcut).encode("utf-8")
    digest = hashlib.sha256(b"win-run-entry-v1\0" + identity).hexdigest()
    return f"wr1-{digest[:24]}"


def preferred_languages() -> list[str]:
    raw = os.environ.get("LANGUAGE") or os.environ.get("LC_MESSAGES") or os.environ.get("LANG") or ""
    languages: list[str] = []
    for item in raw.split(":"):
        item = item.split(".", 1)[0].split("@", 1)[0]
        if not item or item in {"C", "POSIX"}:
            continue
        languages.append(item)
        if "_" in item:
            languages.append(item.split("_", 1)[0])
    return languages


def localized(section: configparser.SectionProxy, key: str) -> str:
    for language in preferred_languages():
        localized_key = f"{key}[{language}]"
        if localized_key in section:
            return desktop_value(section[localized_key])
    return desktop_value(section.get(key, ""))


def icon_score(path: Path) -> tuple[int, int, str]:
    dimensions = next((part for part in reversed(path.parts) if ICON_SIZE_RE.match(part)), "")
    match = ICON_SIZE_RE.match(dimensions)
    area = int(match.group(1)) * int(match.group(2)) if match else 0
    png = 1 if path.suffix.casefold() == ".png" else 0
    return area, png, str(path)


def resolve_icon(root: Path, value: str) -> str:
    if not value:
        return ""
    icon = Path(value).expanduser()
    if icon.is_absolute():
        return str(icon) if icon.is_file() else ""

    icons_root = root / "icons"
    if icons_root.is_dir():
        names = {value, f"{value}.png", f"{value}.svg", f"{value}.xpm"}
        candidates = [path for path in icons_root.rglob("*") if path.is_file() and path.name in names]
        if candidates:
            return str(max(candidates, key=icon_score))
    # A theme icon name is still a useful fallback for Nereid.
    return value if "/" not in value else ""


def read_entry(path: Path, root: Path) -> dict[str, str | bool]:
    parser = configparser.ConfigParser(interpolation=None, strict=False)
    parser.optionxform = str
    with path.open(encoding="utf-8-sig") as file:
        parser.read_file(file)
    if "Desktop Entry" not in parser:
        raise WinRunError("missing [Desktop Entry] section")
    section = parser["Desktop Entry"]
    if section.get("Type", "Application") != "Application":
        raise WinRunError("Desktop Entry is not an application")

    name = localized(section, "Name")
    if not name:
        raise WinRunError("Desktop Entry has no Name")
    shortcut = shortcut_from_exec(section.get("Exec", ""))
    hidden = section.get("NoDisplay", "false").strip().casefold() == "true"
    description = localized(section, "Comment") or localized(section, "GenericName")
    return {
        "id": entry_id(shortcut),
        "shortcut": shortcut,
        "name": name,
        "description": description,
        "icon": resolve_icon(root, section.get("Icon", "")),
        "hidden": hidden or bool(UNINSTALL_RE.search(name)),
    }


def entries(root: Path, *, include_hidden: bool = False) -> list[dict[str, str | bool]]:
    root = shortcuts_root(root)
    if not root.is_dir():
        return []

    unique: dict[str, dict[str, str | bool]] = {}
    for path in sorted(root.glob("*.desktop"), key=lambda item: item.name.casefold()):
        try:
            item = read_entry(path, root)
        except (OSError, UnicodeError, configparser.Error, WinRunError) as error:
            print(f"{APP}: ignoring {path.name}: {error}", file=sys.stderr)
            continue
        if item["hidden"] and not include_hidden:
            continue
        unique.setdefault(str(item["id"]), item)
    return sorted(unique.values(), key=lambda item: (str(item["name"]).casefold(), str(item["id"])))


def list_command() -> int:
    projected = [
        {
            "name": item["name"],
            "exec": f"win-run launch {item['id']}",
            "icon": item["icon"],
            "description": item["description"],
        }
        for item in entries(workspace())
    ]
    print(json.dumps(projected, ensure_ascii=False, separators=(",", ":")))
    return 0


def runtime_environment(root: Path) -> dict[str, str]:
    proton = os.environ.get("WIN_RUN_PROTON", DEFAULT_PROTON)
    umu = os.environ.get("WIN_RUN_UMU", DEFAULT_UMU)
    if not Path(proton).is_dir():
        raise WinRunError(f"Proton is not available at {proton}")
    if not Path(umu).is_file():
        raise WinRunError(f"UMU launcher is not available at {umu}")

    environment = os.environ.copy()
    environment.update(
        {
            "GAMEID": "win-run-default",
            "STORE": "none",
            "WINEPREFIX": str(root),
            "PROTONPATH": proton,
            "PROTON_VERB": "run",
            "UMU_CONTAINER_NSENTER": "1",
        }
    )
    environment.pop("UMU_USE_STEAM", None)
    return environment


def bus_name(root: Path) -> str:
    # This is UMU's documented launcher-service identity for a prefix.
    digest = hashlib.md5(str(root).encode("utf-8"), usedforsecurity=False).hexdigest()
    return f"--bus-name=com.steampowered.App{digest}"


def launch_clients() -> list[Path]:
    override = os.environ.get("WIN_RUN_LAUNCH_CLIENT")
    if override:
        return [Path(override)]
    data_home = Path(os.environ.get("XDG_DATA_HOME", "~/.local/share")).expanduser()
    return sorted(data_home.glob("umu/*/pressure-vessel/bin/steam-runtime-launch-client"))


def service_active(root: Path) -> bool:
    expected = bus_name(root)
    for client in launch_clients():
        if not client.is_file():
            continue
        try:
            result = subprocess.run(
                [str(client), "--list"],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
                timeout=2,
            )
        except (OSError, subprocess.TimeoutExpired):
            continue
        if expected in result.stdout.splitlines():
            return True
    return False


def wait_for_startup(process: subprocess.Popen[bytes], root: Path) -> None:
    timeout = float(os.environ.get("WIN_RUN_STARTUP_TIMEOUT", "15"))
    deadline = time.monotonic() + max(timeout, 0)
    while process.poll() is None and time.monotonic() < deadline:
        if service_active(root):
            return
        time.sleep(0.1)


def run_umu(target: str, arguments: list[str]) -> int:
    root = workspace()
    root.mkdir(parents=True, exist_ok=True)
    environment = runtime_environment(root)
    umu = os.environ.get("WIN_RUN_UMU", DEFAULT_UMU)

    lock_path = root / ".win-run-startup.lock"
    with lock_path.open("a+b") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        already_active = service_active(root)
        try:
            process = subprocess.Popen([umu, target, *arguments], env=environment)
        except OSError as error:
            raise WinRunError(f"could not start UMU: {error}") from error
        if not already_active:
            wait_for_startup(process, root)
        fcntl.flock(lock, fcntl.LOCK_UN)

    status = process.wait()
    return status if status >= 0 else 128 - status


def open_command(arguments: list[str]) -> int:
    if not arguments:
        raise WinRunError("usage: win-run open <file.exe|file.msi> [-- <arguments>...]")
    target = Path(arguments[0]).expanduser()
    extra = arguments[1:]
    if extra:
        if extra[0] != "--":
            raise WinRunError("arguments for the Windows program must follow --")
        extra = extra[1:]
    if not target.is_file():
        raise WinRunError(f"target does not exist or is not a file: {target}")
    if target.suffix.casefold() not in {".exe", ".msi"}:
        raise WinRunError(f"unsupported file type: {target.suffix or '(none)'}")
    return run_umu(str(target.absolute()), extra)


def launch_command(arguments: list[str]) -> int:
    if len(arguments) != 1 or not ENTRY_ID_RE.fullmatch(arguments[0]):
        raise WinRunError("usage: win-run launch <entry-id>")
    requested = arguments[0]
    item = next((entry for entry in entries(workspace()) if entry["id"] == requested), None)
    if item is None:
        raise WinRunError(f"unknown entry ID: {requested}")
    return run_umu(str(item["shortcut"]), [])


def migrate_command(arguments: list[str]) -> int:
    if arguments:
        raise WinRunError("usage: win-run migrate")
    source = legacy_workspace()
    destination = workspace()
    destination.parent.mkdir(parents=True, exist_ok=True)

    lock_path = destination.parent / ".win-run-migration.lock"
    with lock_path.open("a+b") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        source_exists = source.exists()
        destination_exists = destination.exists()
        if source_exists and destination_exists:
            raise WinRunError(f"both source and destination exist: {source}; {destination}")
        if not source_exists:
            return 0
        if service_active(source) or service_active(destination):
            raise WinRunError("cannot migrate while the workspace runtime is active")

        try:
            source.rename(destination)
        except OSError as error:
            raise WinRunError(f"could not move workspace: {error}") from error

        try:
            status = run_umu("createprefix", [])
            if status != 0:
                raise WinRunError(f"UMU prefix update failed with status {status}")
            entries(destination)
        except BaseException:
            if destination.exists() and not source.exists():
                destination.rename(source)
            raise
    print(f"{APP}: migrated {source} to {destination}", file=sys.stderr)
    return 0


def main(arguments: list[str]) -> int:
    if not arguments or arguments[0] in {"-h", "--help"}:
        print("usage: win-run {open|launch|list|migrate} ...", file=sys.stderr)
        return 0 if arguments else 2
    command, rest = arguments[0], arguments[1:]
    commands = {
        "open": open_command,
        "launch": launch_command,
        "list": lambda args: list_command() if not args else (_ for _ in ()).throw(WinRunError("usage: win-run list")),
        "migrate": migrate_command,
    }
    if command not in commands:
        raise WinRunError(f"unknown command: {command}")
    return commands[command](rest)


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except WinRunError as error:
        print(f"{APP}: {error}", file=sys.stderr)
        raise SystemExit(2) from None
