name: Check nix flake

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Check flake evaluation
        run: nix flake check --no-build --all-systems --show-trace
